version: '3'

services:
  proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      # - 443:443
    restart: on-failure:3

  api:
      build:
        context: ./api
      # ports:
      #   - 5000:5000
      volumes:
        - ./downloads:/downloads
        - ./api:/app
        - ./logs:/app/logs
      environment:
        - FLASK_ENVIRONMENT=prod
        - POSTGRES_HOST=db
      env_file:
        - ./.env
      depends_on:
        - db
      restart: on-failure:3

  ui:
      build:
        context: ./ui
      volumes:
        - ./ui:/app
      # ports:
      #   - 3000:3000
      env_file:
        - ./.env
      restart: on-failure:3

  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: on-failure:3